@startuml
actor 入力担当者
boundary ブラウザ
control 在庫管理WebApp
control LockService
entity GoogleSpreadSheet

== 初期起動シーケンス ==
autonumber "[000]"
入力担当者 -> ブラウザ : 在庫管理Webにアクセス
ブラウザ -> 在庫管理WebApp : ページをリクエスト
在庫管理WebApp-> GoogleSpreadSheet :在庫数問い合わせ
在庫管理WebApp -> ブラウザ : ページ
GoogleSpreadSheet -> 在庫管理WebApp : 在庫数
在庫管理WebApp --> ブラウザ : 在庫数
ブラウザ -> ブラウザ : 在庫数書換

== 販売数入力 ==
autonumber "[100]"
alt 販売数増やす
入力担当者 -> ブラウザ : +1ボタンクリック
ブラウザ -> ブラウザ : 販売数を+1して書換
else 販売数減らす
入力担当者 -> ブラウザ : -1ボタンクリック
ブラウザ -> ブラウザ : 販売数を-1して書換
else 販売数クリア
入力担当者 -> ブラウザ : CLRボタンクリック
ブラウザ -> ブラウザ : 販売数を0に書換
end

== 在庫数登録 ==
autonumber "[200]"
入力担当者 -> ブラウザ : 在庫数更新ボタンクリック

alt 販売数==0のとき
ブラウザ -> ブラウザ : 「在庫数に変更はありません」と表示
else 販売数<>0のとき
ブラウザ -> 在庫管理WebApp : 販売数を与え、在庫数の更新を依頼
在庫管理WebApp -> LockService : GoogleSpreadSheetの排他ロックを取得
note left
  https://developers.google.com/apps-script/reference/lock
end note
在庫管理WebApp -> GoogleSpreadSheet : 現在の在庫数を取得
在庫管理WebApp -> GoogleSpreadSheet : 在庫数を（在庫数-販売数）に書換
在庫管理WebApp -> LockService : GoogleSpreadSheetの排他ロックを解除
在庫管理WebApp  --> ブラウザ : 新在庫数を通知
ブラウザ -> ブラウザ : 在庫数を新在庫数に更新
end

@enduml