@startuml
actor 入力担当者
boundary ブラウザ
control 在庫管理WebApp
entity GoogleSpreadSheet

== 初期起動シーケンス ==
autonumber "[000]"
入力担当者 -> ブラウザ : 在庫管理Webにアクセス
ブラウザ -> 在庫管理WebApp : ページをリクエスト
在庫管理WebApp-> GoogleSpreadSheet :在庫数問い合わせ
在庫管理WebApp -> ブラウザ : ページ
GoogleSpreadSheet -> 在庫管理WebApp : 在庫数
在庫管理WebApp --> ブラウザ : 在庫数
ブラウザ -> ブラウザ : 在庫数書換

== 販売数入力 ==
autonumber "[100]"
alt 販売数増やす
入力担当者 -> ブラウザ : +1ボタンクリック
ブラウザ -> ブラウザ : 販売数を+1して書換
else 販売数減らす
入力担当者 -> ブラウザ : -1ボタンクリック
ブラウザ -> ブラウザ : 販売数を-1して書換
else 販売数クリア
入力担当者 -> ブラウザ : CLRボタンクリック
ブラウザ -> ブラウザ : 販売数を0に書換
end

== 在庫数登録 ==
autonumber "[200]"
入力担当者 -> ブラウザ : 在庫数更新ボタンクリック

alt 販売数==0のとき
ブラウザ -> ブラウザ : 「在庫数に変更はありません」と表示
else 販売数<>0のとき
ブラウザ -> ブラウザ : 在庫数を（在庫数-販売数）に書換
ブラウザ -> GoogleSpreadSheet : 在庫数変更
GoogleSpreadSheet --> ブラウザ : 新在庫数
ブラウザ -> ブラウザ : 「在庫数を（新在庫数）に変更しました」と表示
end

@enduml